### ISSUE TITLE
cannot parse schema string from delta table metadata

### ISSUE THREAD

**Issue by giulianopz** [csimplestring/delta-go#21]
When getting the schema from the metadata of a given delta table, `Metadata.Schema()` fails due to a type conversion  error.

To reproduce the error, run this slightly modified test in the repo:
```go
package examples

import (
	"log"
	"path/filepath"
	"testing"

	delta "github.com/csimplestring/delta-go"
)

func TestLocalExample(t *testing.T) {

	path, err := filepath.Abs("../tests/golden/snapshot-data0")
	if err != nil {
		log.Fatal(err)
	}

	path = "file://" + path + "/"

	config := delta.Config{
		StoreType: "file",
	}

	table, err := delta.ForTable(path, config, &delta.SystemClock{})
	if err != nil {
		log.Fatal(err)
	}

	s, err := table.Snapshot()
	if err != nil {
		log.Fatal(err)
	}

	version := s.Version()
	log.Println(version)

	files, err := s.AllFiles()

	for _, f := range files {
		log.Println(f.Path)
	}

	metadata, err := s.Metadata()
	if err != nil {
		log.Fatal(err)
	}

	schema, err := metadata.Schema() /* this throws an error*/
	if err != nil {
		log.Fatal(err)
	}

	for _, f := range schema.GetFields() {
		log.Default().Println("name=", f.Name, "type=", f.DataType)
	}
}
--------------------
2023/06/26 23:47:55 0
2023/06/26 23:47:55 part-00000-0441e99a-c421-400e-83a1-212aa6c84c73-c000.snappy.parquet
2023/06/26 23:47:55 part-00001-34c8c673-3f44-4fa7-b94e-07357ec28a7d-c000.snappy.parquet
2023/06/26 23:47:55 fail to convert integer to a DataType: 
FAIL	github.com/csimplestring/delta-go/examples	2.016s
FAIL
```

This is the json schema which the lib fails to parse:
```yaml
{
    "type": "struct",
    "fields": [
        {
            "name": "col1",
            "type": "integer",
            "nullable": true,
            "metadata": {}
        },
        {
            "name": "col2",
            "type": "string",
            "nullable": true,
            "metadata": {}
        }
    ]
}
```

The problem is caused by the func `nameToType` expecting to match the string "int" to `IntegerType` instead of `integer`. 
The Delta [protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#schema-serialization-format) mentions "integer" as a primitive type, not "int". 
I know that this Go implementation closely mirrors the Scala [native library](https://github.com/delta-io/connectors/blob/dbf26557c485a9fd7c7f71e393ee186fc02ca2fc/standalone/src/main/scala/io/delta/standalone/internal/util/DataTypeParser.scala#L148), so I cannot really understand why this error happens. 
Additionally, as far as I know, no [breaking changes](https://docs.delta.io/latest/versioning.html) altered the protocol with respect to the schema serialization format.
